# Generated by Django 4.0.5 on 2023-03-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_authusers_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='authusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
