# Generated by Django 4.0.5 on 2023-03-09 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_authusers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='authusers',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='authusers',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
