# Generated by Django 4.1 on 2023-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_authusers_email_alter_authusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='cover/default_cover_image.png', upload_to='covers/'),
        ),
    ]
