# Generated by Django 4.1.7 on 2023-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.CharField(blank=True, choices=[('na', 'na'), ('principal', 'Principal'), ('lecturer', 'Lecturer'), ('pune', 'Pune'), ('student', 'Student'), ('others', 'Other staff')], default='na', max_length=20),
        ),
    ]
