# Generated by Django 4.0.5 on 2023-03-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_authusers_date_created_alter_authusers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='authusers',
            name='user',
            field=models.TextField(blank=True, default='', primary_key=True, serialize=False),
        ),
    ]
