# Generated by Django 4.0.5 on 2023-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_authusers_id_alter_authusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authusers',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authusers',
            name='user',
            field=models.TextField(blank=True, default=''),
        ),
    ]
