# Generated by Django 4.1 on 2023-03-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='cover/default_cover_image.png', upload_to='covers/'),
        ),
    ]
