# Generated by Django 4.1.7 on 2023-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_usersettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='cover/default_cover_image.png', null=True, upload_to='covers/'),
        ),
    ]
