# Generated by Django 4.1.7 on 2023-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_user_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('na', 'na'), ('cse', 'Compter Science and Engineering'), ('ise', 'Information Science and Engineering'), ('aids', 'Artificial Intellingence & Data Science'), ('ece', 'Electronics and Communication Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('ce', 'Civil Engineering')], default='na', max_length=20),
        ),
    ]
