# Generated by Django 4.1.7 on 2023-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_user_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default_cover_image.jpg', upload_to='covers/'),
        ),
    ]
