# Generated by Django 5.0.4 on 2024-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_alter_user_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('na', 'na'), ('bca', 'Bachelor of Computer Application'), ('bcom', 'Bachelor of Commerce'), ('ba', 'Bachelor of Arts')], default='na', max_length=20),
        ),
    ]
